apiVersion: v1
kind: Secret
metadata:
  name: atlantis-github
  namespace: atlantis
type: Opaque
stringData:
  github-user:   "kajal-nerkar"
  github-token:  "<github-token>"
  webhook-secret: "<webhook-secret>"
