apiVersion: v1
kind: Secret
metadata:
  name: atlantis-github
  namespace: atlantis
type: Opaque
stringData:
  github-user:   "kajal-nerkar"
  github-token:  "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"
  webhook-secret: "fcb70c47ae65e2d2e41bc0548b999cd3"
